name: strip_markdown
description: A starting point for Dart libraries or applications.
version: 1.0.0
repository: https://github.com/FaFre/strip_markdown

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lint: ^2.8.0
  test: ^1.24.0
